# Generated by Django 2.0.3 on 2018-03-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthyrecipeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
